<?php


namespace The\ObjectNamespace;


use Ling\SimplePdoWrapper\SimplePdoWrapperInterface;
// use


/**
 * The MyFactoryObjectFactory class.
 */
class MyFactoryObjectFactory
{

    /**
     * This property holds the pdoWrapper for this instance.
     * @var SimplePdoWrapperInterface
     */
    protected $pdoWrapper;

//::extraProperties--definition

    /**
     * Builds the MyFactoryObjectFactory instance.
     */
    public function __construct()
    {
        $this->pdoWrapper = null;
//::extraProperties--instantiation
    }

// getXXX



    //--------------------------------------------
    //
    //--------------------------------------------
    /**
     * Sets the pdoWrapper.
     *
     * @param SimplePdoWrapperInterface $pdoWrapper
     */
    public function setPdoWrapper(SimplePdoWrapperInterface $pdoWrapper)
    {
        $this->pdoWrapper = $pdoWrapper;
    }

//::extraPublicMethods
}
