<?php


namespace The\ObjectNamespace;


use Ling\SimplePdoWrapper\SimplePdoWrapperInterface;
use Ling\SimplePdoWrapper\SimplePdoWrapper;
//::extraUseStatements


/**
 * The UserObject class.
 */
class UserObject implements UserObjectInterface
{

    /**
     * This property holds the pdoWrapper for this instance.
     * @var SimplePdoWrapperInterface
     */
    protected $pdoWrapper;

//::extraProperties--definition

    /**
     * Builds the UserObject instance.
     */
    public function __construct()
    {
        $this->pdoWrapper = null;
//::extraProperties--instantiation
    }




// insertXXX

// getXXX

// updateXXX

// deleteXXX


    //--------------------------------------------
    //
    //--------------------------------------------
    /**
     * Sets the pdoWrapper.
     *
     * @param SimplePdoWrapperInterface $pdoWrapper
     */
    public function setPdoWrapper(SimplePdoWrapperInterface $pdoWrapper)
    {
        $this->pdoWrapper = $pdoWrapper;
    }


//::extraPublicMethods


    //--------------------------------------------
    //
    //--------------------------------------------
// doInsertXXX

// doGetXXX

// doUpdateXXX

// doDeleteXXX


    //--------------------------------------------
    //
    //--------------------------------------------
//::extraProtectedMethods

}
