<?php


namespace The\ObjectNamespace;

use Ling\SimplePdoWrapper\SimplePdoWrapper;
use Ling\SimplePdoWrapper\Util\Where;
use Ling\SimplePdoWrapper\Exception\SimplePdoWrapperQueryException;
// the uses


/**
 * The UserObject class.
 */
class UserObject extends BaseParent implements UserObjectInterface
{


    /**
     * Builds the UserObject instance.
     */
    public function __construct()
    {
        parent::__construct();
        $this->table = "theTableName";
    }




// insertXXX

// multipleInsertXXX

// getXXX

// getTheItem

// getTheItems

// getThe_ItemsColumn

// getThe_Items_Columns

// getThe_Items_Key2Value

// getIdByXXX

// getItemsByHas

// getItemXXXByHas

// getAllXXX

// updateXXX

// deleteYYY

// deleteXXX

// deletesXXX




}
