<?php


namespace The\ObjectNamespace;

use Ling\SimplePdoWrapper\SimplePdoWrapper;
// the uses


/**
 * The UserObject class.
 */
class UserObject extends BaseParent implements UserObjectInterface
{


    /**
     * Builds the UserObject instance.
     */
    public function __construct()
    {
        parent::__construct();
        $this->table = "theTableName";
    }




// insertXXX

// getXXX

// getTheItem

// getTheItems

// getIdByXXX

// getItemsByHas

// getItemXXXByHas

// getAllXXX

// updateXXX

// deleteXXX




}
