<?php


namespace The\ObjectNamespace;


/**
 * The UserObjectInterface interface.
 * It implements the @page(ling standard object methods) concept.
 */
interface UserObjectInterface
{


// insertXXX

// multipleInsertXXX

// fetchFetchAllXXX

// getXXX

// getTheItem

// getTheItems

// getThe_Items_Column

// get_The_Items_Columns

// get_The_Items_Key2Value

// getIdByXXX

// getItemsByForeignKeys

// getItemsByHas

// getItemXXXByHas

// getAllXXX

// updateXXX

// updateRawXXX

// deleteYYY

// deleteXXX

// deletesXXX

// deleteByFkXXX

}
