-- MySQL Script generated by MySQL Workbench
-- Tue Jun  9 08:06:46 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
-- SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
-- SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `lud_user_group`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lud_user_group` ;

CREATE TABLE IF NOT EXISTS `lud_user_group` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lud_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lud_user` ;

CREATE TABLE IF NOT EXISTS `lud_user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_group_id` INT NOT NULL,
  `identifier` VARCHAR(128) NOT NULL,
  `pseudo` VARCHAR(64) NOT NULL,
  `email` VARCHAR(128) NOT NULL,
  `password` VARCHAR(64) NOT NULL,
  `avatar_url` VARCHAR(512) NOT NULL,
  `extra` TEXT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `identifier_UNIQUE` (`identifier` ASC),
  INDEX `fk_lud_user_lud_user_group1_idx` (`user_group_id` ASC),
  CONSTRAINT `fk_lud_user_lud_user_group1`
    FOREIGN KEY (`user_group_id`)
    REFERENCES `lud_user_group` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lud_permission_group`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lud_permission_group` ;

CREATE TABLE IF NOT EXISTS `lud_permission_group` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lud_permission`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lud_permission` ;

CREATE TABLE IF NOT EXISTS `lud_permission` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lud_user_has_permission_group`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lud_user_has_permission_group` ;

CREATE TABLE IF NOT EXISTS `lud_user_has_permission_group` (
  `user_id` INT NOT NULL,
  `permission_group_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `permission_group_id`),
  INDEX `fk_lud_user_has_lud_permission_group_lud_permission_group1_idx` (`permission_group_id` ASC),
  INDEX `fk_lud_user_has_lud_permission_group_lud_user_idx` (`user_id` ASC),
  CONSTRAINT `fk_lud_user_has_lud_permission_group_lud_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `lud_user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_lud_user_has_lud_permission_group_lud_permission_group1`
    FOREIGN KEY (`permission_group_id`)
    REFERENCES `lud_permission_group` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lud_permission_group_has_permission`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lud_permission_group_has_permission` ;

CREATE TABLE IF NOT EXISTS `lud_permission_group_has_permission` (
  `permission_group_id` INT NOT NULL,
  `permission_id` INT NOT NULL,
  PRIMARY KEY (`permission_group_id`, `permission_id`),
  INDEX `fk_lud_permission_group_has_lud_permission_lud_permission1_idx` (`permission_id` ASC),
  INDEX `fk_lud_permission_group_has_lud_permission_lud_permission_g_idx` (`permission_group_id` ASC),
  CONSTRAINT `fk_lud_permission_group_has_lud_permission_lud_permission_gro1`
    FOREIGN KEY (`permission_group_id`)
    REFERENCES `lud_permission_group` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_lud_permission_group_has_lud_permission_lud_permission1`
    FOREIGN KEY (`permission_id`)
    REFERENCES `lud_permission` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lud_plugin_option`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lud_plugin_option` ;

CREATE TABLE IF NOT EXISTS `lud_plugin_option` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `category` VARCHAR(128) NOT NULL,
  `name` VARCHAR(64) NOT NULL,
  `value` VARCHAR(512) NOT NULL,
  `description` TEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lud_user_group_has_plugin_option`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lud_user_group_has_plugin_option` ;

CREATE TABLE IF NOT EXISTS `lud_user_group_has_plugin_option` (
  `user_group_id` INT NOT NULL,
  `plugin_option_id` INT NOT NULL,
  PRIMARY KEY (`user_group_id`, `plugin_option_id`),
  INDEX `fk_lud_user_group_has_lud_plugin_option_lud_plugin_option1_idx` (`plugin_option_id` ASC),
  INDEX `fk_lud_user_group_has_lud_plugin_option_lud_user_group1_idx` (`user_group_id` ASC),
  CONSTRAINT `fk_lud_user_group_has_lud_plugin_option_lud_user_group1`
    FOREIGN KEY (`user_group_id`)
    REFERENCES `lud_user_group` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_lud_user_group_has_lud_plugin_option_lud_plugin_option1`
    FOREIGN KEY (`plugin_option_id`)
    REFERENCES `lud_plugin_option` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tes_table1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tes_table1` ;

CREATE TABLE IF NOT EXISTS `tes_table1` (
`id` INT NOT NULL AUTO_INCREMENT,
`pseudo` VARCHAR(64) NOT NULL,
`password` VARCHAR(64) NOT NULL,
UNIQUE INDEX `pseudo_UNIQUE` (`pseudo` ASC, `password` ASC),
PRIMARY KEY (`id`))
ENGINE = InnoDB;



-- SET SQL_MODE=@OLD_SQL_MODE;
-- SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
-- SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;



-- @rename table:oldCol->newCol