<?php


namespace Ling\HybridList\HybridListControl;

use Ling\HybridList\HybridListInterface;


/**
 * Hybrid list control
 * =====================
 * On a product list, an hybrid list control is an object responsible for:
 *
 * - creating the model for the hybrid control widget (through which the user interacts with the list)
 * - shape the list of items (either shaping the sql request or even the php rows directly) so that
 *      the generated list reacts to the parameters generated by the widget
 *
 *
 *
 */
interface HybridListControlInterface
{

    /**
     *
     * This method is used to shape the list of items (using either the request part, or the dynamic php part).
     *
     *
     * @param HybridListInterface $list
     * @param array $context , given by the caller: useful variables
     * @return HybridListControlInterface
     */
    public function prepareHybridList(HybridListInterface $list, array $context);

    /**
     * @return array, the model for the HybridListControl widget.
     *      prepareHybridList method is called first.
     *
     */
    public function getModel();

}