-- MySQL Script generated by MySQL Workbench
-- Thu Aug 13 10:51:06 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `lun_user_notification`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lun_user_notification` ;

CREATE TABLE IF NOT EXISTS `lun_user_notification` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `lud_user_id` INT NOT NULL,
  `feeder` VARCHAR(64) NOT NULL,
  `type` VARCHAR(64) NOT NULL,
  `message` VARCHAR(512) NOT NULL,
  `status` TINYINT(1) NOT NULL,
  `date_creation` DATETIME NOT NULL,
  `date_deletion` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_lun_user_notification_lud_user_idx` (`lud_user_id` ASC),
  CONSTRAINT `fk_lun_user_notification_lud_user`
    FOREIGN KEY (`lud_user_id`)
    REFERENCES `lud_user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
