-- MySQL Script generated by MySQL Workbench
-- Tue Apr  6 09:25:32 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `lke_widget`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lke_widget` ;

CREATE TABLE IF NOT EXISTS `lke_widget` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `identifier` VARCHAR(128) NOT NULL,
  `name` VARCHAR(128) NOT NULL,
  `type` VARCHAR(32) NOT NULL,
  `classname` VARCHAR(256) NOT NULL,
  `widget_dir` VARCHAR(256) NOT NULL,
  `template` VARCHAR(64) NOT NULL,
  `js` VARCHAR(64) NOT NULL,
  `skin` VARCHAR(64) NOT NULL,
  `vars` TEXT NOT NULL,
  `active` TINYINT(2) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `identifier_UNIQUE` (`identifier` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lke_block`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lke_block` ;

CREATE TABLE IF NOT EXISTS `lke_block` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `identifier` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `identifier_UNIQUE` (`identifier` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lke_site`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lke_site` ;

CREATE TABLE IF NOT EXISTS `lke_site` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `identifier` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `identifier_UNIQUE` (`identifier` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lke_page`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lke_page` ;

CREATE TABLE IF NOT EXISTS `lke_page` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `site_id` INT NOT NULL,
  `identifier` VARCHAR(128) NOT NULL,
  `label` VARCHAR(128) NOT NULL,
  `layout` VARCHAR(256) NOT NULL,
  `layout_vars` TEXT NOT NULL,
  `title` VARCHAR(128) NOT NULL,
  `description` VARCHAR(512) NOT NULL,
  `bodyclass` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `identifier_UNIQUE` (`identifier` ASC),
  INDEX `fk_lke_page_lke_site1_idx` (`site_id` ASC),
  CONSTRAINT `fk_lke_page_lke_site1`
    FOREIGN KEY (`site_id`)
    REFERENCES `lke_site` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lke_block_has_widget`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lke_block_has_widget` ;

CREATE TABLE IF NOT EXISTS `lke_block_has_widget` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `block_id` INT NOT NULL,
  `widget_id` INT NOT NULL,
  `position` TINYINT(4) NOT NULL,
  INDEX `fk_lke_block_has_lke_widget_lke_widget1_idx` (`widget_id` ASC),
  INDEX `fk_lke_block_has_lke_widget_lke_block1_idx` (`block_id` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_lke_block_has_lke_widget_lke_block1`
    FOREIGN KEY (`block_id`)
    REFERENCES `lke_block` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_lke_block_has_lke_widget_lke_widget1`
    FOREIGN KEY (`widget_id`)
    REFERENCES `lke_widget` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lke_page_has_block`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lke_page_has_block` ;

CREATE TABLE IF NOT EXISTS `lke_page_has_block` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `page_id` INT NOT NULL,
  `block_id` INT NOT NULL,
  `position_name` VARCHAR(64) NOT NULL,
  `block_index` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_lke_page_has_lke_block_lke_block1_idx` (`block_id` ASC),
  INDEX `fk_lke_page_has_lke_block_lke_page1_idx` (`page_id` ASC),
  CONSTRAINT `fk_lke_page_has_lke_block_lke_page1`
    FOREIGN KEY (`page_id`)
    REFERENCES `lke_page` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_lke_page_has_lke_block_lke_block1`
    FOREIGN KEY (`block_id`)
    REFERENCES `lke_block` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
