-- MySQL Script generated by MySQL Workbench
-- Fri Jul 31 15:11:54 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `tes_table1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tes_table1` ;

CREATE TABLE IF NOT EXISTS `tes_table1` (
`id` INT NOT NULL AUTO_INCREMENT,
`pseudo` VARCHAR(64) NOT NULL,
`password` VARCHAR(64) NOT NULL,
UNIQUE INDEX `pseudo_UNIQUE` (`pseudo` ASC, `password` ASC),
PRIMARY KEY (`id`))
ENGINE = InnoDB;



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
