-- MySQL Script generated by MySQL Workbench
-- Tue Apr  6 14:41:27 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `lks_website`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lks_website` ;

CREATE TABLE IF NOT EXISTS `lks_website` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `provider` VARCHAR(64) NOT NULL,
  `identifier` VARCHAR(64) NOT NULL,
  `vendor_name` VARCHAR(64) NOT NULL,
  `vendor_url` VARCHAR(256) NOT NULL,
  `description` TEXT NOT NULL,
  `post_datetime` DATETIME NOT NULL,
  `price_in_euro` DECIMAL(10,2) NOT NULL,
  `screenshots` TEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lks_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lks_user` ;

CREATE TABLE IF NOT EXISTS `lks_user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(128) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lks_user_rates_website`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lks_user_rates_website` ;

CREATE TABLE IF NOT EXISTS `lks_user_rates_website` (
  `user_id` INT NOT NULL,
  `website_id` INT NOT NULL,
  `rating_1_to_5` TINYINT NOT NULL,
  PRIMARY KEY (`user_id`, `website_id`),
  INDEX `fk_lks_user_has_lks_website_lks_website1_idx` (`website_id` ASC),
  INDEX `fk_lks_user_has_lks_website_lks_user_idx` (`user_id` ASC),
  CONSTRAINT `fk_lks_user_has_lks_website_lks_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `lks_user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_lks_user_has_lks_website_lks_website1`
    FOREIGN KEY (`website_id`)
    REFERENCES `lks_website` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
