-- MySQL Script generated by MySQL Workbench
-- Fri Nov 27 16:05:21 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `lln_connexion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lln_connexion` ;

CREATE TABLE IF NOT EXISTS `lln_connexion` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_identifier` VARCHAR(128) NOT NULL,
  `user_id` VARCHAR(32) NOT NULL,
  `user_email` VARCHAR(128) NOT NULL,
  `login_date` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
