-- MySQL Script generated by MySQL Workbench
-- Thu Nov  5 10:55:05 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `luda_tag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `luda_tag` ;

CREATE TABLE IF NOT EXISTS `luda_tag` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;



-- -----------------------------------------------------
-- Table `luda_resource`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `luda_resource` ;

CREATE TABLE IF NOT EXISTS `luda_resource` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `lud_user_id` INT NOT NULL,
  `canonical` VARCHAR(64) NOT NULL,
  `is_private` CHAR(1) NOT NULL,
  `date_creation` DATETIME NOT NULL,
  `date_last_update` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_luda_resource_lud_user1_idx` (`lud_user_id` ASC),
  UNIQUE INDEX `lud_user_id_UNIQUE` (`lud_user_id` ASC, `canonical` ASC),
  CONSTRAINT `fk_luda_resource_lud_user1`
    FOREIGN KEY (`lud_user_id`)
    REFERENCES `lud_user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `luda_resource_has_tag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `luda_resource_has_tag` ;

CREATE TABLE IF NOT EXISTS `luda_resource_has_tag` (
  `resource_id` INT NOT NULL,
  `tag_id` INT NOT NULL,
  PRIMARY KEY (`resource_id`, `tag_id`),
  INDEX `fk_luda_resource_has_luda_tag_luda_tag1_idx` (`tag_id` ASC),
  INDEX `fk_luda_resource_has_luda_tag_luda_resource_idx` (`resource_id` ASC),
  CONSTRAINT `fk_luda_resource_has_luda_tag_luda_resource`
    FOREIGN KEY (`resource_id`)
    REFERENCES `luda_resource` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_luda_resource_has_luda_tag_luda_tag1`
    FOREIGN KEY (`tag_id`)
    REFERENCES `luda_tag` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `luda_resource_file`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `luda_resource_file` ;

CREATE TABLE IF NOT EXISTS `luda_resource_file` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `luda_resource_id` INT NOT NULL,
  `path` VARCHAR(256) NOT NULL,
  `nickname` VARCHAR(64) NOT NULL,
  `is_source` CHAR(1) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_luda_resource_file_luda_resource1_idx` (`luda_resource_id` ASC),
  CONSTRAINT `fk_luda_resource_file_luda_resource1`
    FOREIGN KEY (`luda_resource_id`)
    REFERENCES `luda_resource` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
