<?php


namespace Module\Example\Api\GeneratedObject;


use Ling\XiaoApi\Object\TableCrudObject;

/**
 * This file was generated by the DbObjectGenerator.
 * You should not edit it manually, otherwise you
 * might loose your edits on the next update.
 *
 * You are supposed to extend this object.
 */
class GeneratedExampleObject extends TableCrudObject
{

    public function __construct()
    {
        parent::__construct();
        $this->table = "theTable";
        $this->primaryKey = [//primaryKey];
    }


    //--------------------------------------------
    //
    //--------------------------------------------
    protected function getCreateData(array $data)
    {
        $base = $array;
        $ret = array_replace($base, array_intersect_key($data, $base));

//-nullables

        return $ret;
    }


}